services:
  db:
    image: mysql:8.0
    container_name: mysql-db-8004
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DB_ECOMMERCE
      MYSQL_USER: django
      MYSQL_PASSWORD: django
    ports:
      - "3307:3306"
    volumes:
      - db_data_8004:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: django-app-8004
    restart: unless-stopped
    environment:
      DJANGO_SECRET_KEY: change-this-secret-key
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,84.8.221.206
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DB_ECOMMERCE
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    ports:
      - "8004:8004"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8004

volumes:
  db_data_8004:
